services:
  mongodb:
    image: mongo:5.0
    container_name: proctoring-mongodb
    restart: unless-stopped
    ports:
      - "25755:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: proctoring

  backend:
    build:
      context: . 
      dockerfile: ./backend/Dockerfile  
    container_name: proctoring-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongodb:27017/proctoring
      PORT: 8000
      FRONTEND_URL: http://localhost:3000
      ALLOWED_ORIGINS: localhost:8000
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb

  frontend:
    build:
      context: .  
      dockerfile: ./frontend/Dockerfile  
    container_name: proctoring-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://localhost:5000/api
      VITE_SOCKET_URL: http://localhost:5000
    depends_on:
      - backend

volumes:
  mongodb_data:
